--alter table public.colect16_load add vyear varchar(4);

--update public.colect16_load set vyear = '2016';

insert into public.colect
    (col_malignancyt,
    col_ileus_unk,
    col_oral_antibiotic,
    col_margins_unk,
    col_emergent,
    col_chemo_unk,
    caseid,
    col_icd9_indication,
    col_indication,
    col_anastomotic,
    col_malignancym,
    col_ileus,
    col_approach,
    col_chemo,
    col_mech_bowel_prep_unk,
    col_malignancyn,
    col_steroid_unk,
    col_nodeseval,
    col_icd9_emergent,
    col_margins,
    col_oral_antibiotic_unk,
    col_steroid,
    col_mech_bowel_prep,
    vyear)
select
    col_malignancyt,
    col_ileus_unk,
    col_oral_antibiotic,
    col_margins_unk,
    col_emergent,
    col_chemo_unk,
    caseid,
    col_icd9_indication,
    col_indication,
    col_anastomotic,
    col_malignancym,
    col_ileus,
    col_approach,
    col_chemo,
    col_mech_bowel_prep_unk,
    col_malignancyn,
    col_steroid_unk,
    col_nodeseval,
    col_icd9_emergent,
    col_margins,
    col_oral_antibiotic_unk,
    col_steroid,
    col_mech_bowel_prep,
    vyear
from colect16_load;